# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1b79c9119fca56f681bf952aa7c84a39b0d64d49f724166c2345d4fe7fbbee5a8e418c3e046cd21f3be88961ebc18937a30c4ab5e9dcfa98c0ffb83a6de4f83

test:
  secret_key_base: 3fbc03d7856a054ae8511501788f739a73b8862f3b1aaef3075f64bd4f1428a44955cd744d640ed3a3952347e16870ae4fabf6ff7a84de63e0346620252d0f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
